{{- $dashboard := true -}}
{{- $dashboard_host := env "WYGA_SITE_DASHBOARD" -}}
{{- $dashboard_https := true -}}
{{- if eq $dashboard_host "" -}}
{{- $dashboard = false -}}
{{- end -}}
{{- if $dashboard -}}
{{- $dashboard_host = replace "https://" "" $dashboard_host -}}
{{- $dashboard_host = replace "http://" "" $dashboard_host -}}
{{- end -}}
http:
  middlewares:
    http2https:
      redirectScheme:
        scheme: https
        permanent: false

{{ if $dashboard }}
    redirect2dashboard:
      redirectRegex:
        regex: "^/$"
        replacement: "/dashboard/"

  routers:
    traefik-dashboard-https:
      entryPoints:
        - https
      middlewares:
        - redirect2dashboard
      service: api@internal
      rule: Host(`{{ $dashboard_host }}`)
      priority: 999
      tls:
        domains:
          - main: "{{ $dashboard_host }}"
{{ end }}
tls:
  stores:
    default: {}
  options:
    default:
      sniStrict: false
      minVersion: VersionTLS12
      # Based on https://ssl-config.mozilla.org/#server=traefik&version=2.1.2&config=intermediate&guideline=5.6
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
